add pull logic

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -1600,8 +1600,15 @@ runs:
           fi
         # Forked action
         else
-        echo "Using custom prebuilt image"
-        METRICS_IMAGE=ghcr.io/oseconds/test-metrics:latest
+          echo "Using custom prebuilt image"
+
+          METRICS_IMAGE=ghcr.io/oseconds/test-metrics:latest
+
+          echo "Attempting to pull docker image: $METRICS_IMAGE"
+          if ! docker image pull $METRICS_IMAGE; then
+            echo "Failed to pull image, rebuilding"
+            METRICS_IMAGE=metrics:forked-$METRICS_VERSION
+          fi
         fi
 
         # Build image if necessary
